### ISSUE TITLE
George's Contributions

### ISSUE THREAD

**Issue by kittsville** [kittsville/project-1#12]
I was wondering how we were going to do the group contributions on the peer assessment forms. Checking the Google Doc and the project stats, he hasn't actually contributed anything.

Considering it's four hours until the project is due for submission and it's nearly finished (code and report), it's unlikely that he's going to start now.

**Comment by cstewart90** [comment]
Hey kit, what is your name? So that I can add it to peer assessment form.

**Comment by kittsville** [comment]
Christopher Maywood

**Comment by cstewart90** [comment]
Thank you
